# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_machine', '0002_quotesmain_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesmain',
            name='title',
        ),
    ]
