# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-21 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(default=None, max_length=1000, verbose_name='Краткое описание')),
                ('startDate', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['author', '-date_created'],
            },
        ),
    ]
