# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='fulltext',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полный текст'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='shortcontent',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое содержание'),
        ),
    ]
