# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20160614_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
