# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20160623_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
