# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20160624_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
