# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_blogpost_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-creation_date'], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
