# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0012_auto_20160706_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='postDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='postUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
