# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0013_auto_20160707_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='userDownVotes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='userDownVotes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='userUpVotes',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='userUpVotes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
