# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20160707_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='currentVotesSum',
            field=models.IntegerField(default=0, verbose_name='Пользовательский рейтинг'),
        ),
    ]
