# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_blogpost_currentvotessum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='currentVotesSum',
        ),
    ]
