# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_remove_blogpost_currentvotessum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, related_name='postDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, related_name='postUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
