# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_auto_20160708_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_commentable',
            field=models.BooleanField(default=True, verbose_name='Комментарии'),
        ),
    ]
