# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_blogpost_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Задача')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Краткое описание')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Приоритет задачи')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['-priority'],
            },
        ),
    ]
