# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_mytask_is_complited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='is_complited',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
