# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 04:23
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('myblog', '0024_auto_20160713_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytask',
            options={'ordering': ['priority'], 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
