# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_auto_20160715_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='_fulltext_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='_shortcontent_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='fulltext',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, max_length=10000, no_rendered_field=True, null=True, verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='shortcontent',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, max_length=1000, no_rendered_field=True, null=True, verbose_name='Краткое содержание'),
        ),
    ]
