# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 05:31
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0029_auto_20160720_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='fulltext',
            field=redactor.fields.RedactorField(blank=True, max_length=10000, null=True, verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='shortcontent',
            field=redactor.fields.RedactorField(blank=True, max_length=1000, null=True, verbose_name='Краткое содержание'),
        ),
    ]
