# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0030_auto_20160720_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogpost/sliders/', verbose_name='Фон новости'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_slide',
            field=models.BooleanField(default=False, verbose_name='Основной слайд?'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='on_slider',
            field=models.BooleanField(default=False, verbose_name='На слайдере?'),
        ),
    ]
