# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0031_auto_20160817_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blogpost/sliders/', verbose_name='Фон новости'),
        ),
    ]
