# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0036_auto_20160817_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Заглавный слайд?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-creation_date'],
                'verbose_name_plural': 'посты в слайдере',
                'verbose_name': 'пост в слайдере',
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='main_slide',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='on_slider',
        ),
        migrations.AddField(
            model_name='sliderpost',
            name='main_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.BlogPost'),
        ),
    ]
