# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0013_imagepool_is_commentable'),
        ('myblog', '0037_auto_20160818_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpost',
            name='image_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagepool.ImagePool'),
        ),
    ]
