# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0038_sliderpost_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'категории',
                'verbose_name': 'категория',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.PostCategory'),
        ),
    ]
