# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0039_auto_20161108_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
