# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0040_remove_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='myblog.PostCategory', verbose_name='Категория'),
        ),
    ]
