# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0044_auto_20161206_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='shortcontent',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое содержание'),
        ),
    ]
