# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0045_auto_20161206_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='fulltext',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полный текст'),
        ),
    ]
