# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagepool/%Y/%m', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'изображения',
                'verbose_name': 'изображение',
                'ordering': ['user', '-date_upload'],
            },
        ),
    ]
