# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0003_auto_20160721_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'ordering': ['-date_created'], 'verbose_name': 'альбом', 'verbose_name_plural': 'альбомы'},
        ),
    ]
