# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0006_auto_20160722_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='imagepool',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
