# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0008_imagepool_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepool',
            name='is_cover',
        ),
    ]
