# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0009_remove_imagepool_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepool',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Обложка альбома?'),
        ),
    ]
