# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0010_imagepool_is_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepool',
            name='image',
            field=models.ImageField(default=None, upload_to='C:/static/media/imagepool/%Y/%m', verbose_name='Изображение'),
        ),
    ]
