# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepool', '0011_auto_20160816_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepool',
            name='image',
            field=models.ImageField(default=None, upload_to='imagepool/%Y/%m', verbose_name='Изображение'),
        ),
    ]
